// Test-only page bootstrap. Tutorial engine/config and page markup/CSS are production files.
const options = await fetch('/options').then(r => r.json());
window.fixtureErrors = [];
window.addEventListener('error', e => window.fixtureErrors.push(e.message));
window.addEventListener('unhandledrejection', e => window.fixtureErrors.push(String(e.reason)));
window.ACEAuth = { async request(url, init = {}) {
  const response = await fetch(url, { ...init, headers: { 'Content-Type': 'application/json' } });
  const body = await response.json();
  if (!response.ok) throw new Error(body.error);
  return body;
} };
const { profile } = await window.ACEAuth.request('/v1/me');
window.AppState = { currentUser: window.fixtureProfileRecord(profile), isClockedIn: Boolean(options.clockedIn), assignedSchedule: options.schedule ? { name: 'Fixture flex', schedule_type: 'FLEX', daily_elapsed_minutes: 480 } : null };
document.body.classList.remove('app-shell-pending');
document.querySelector('.app-shell-skeleton')?.remove();
const role = profile.role;
const groups = new Map();
for (const step of window.ACETutorialConfig[role].steps) {
  if (!step.navigation) continue;
  const group = groups.get(step.navigation.group) || new Map();
  group.set(step.navigation.label, step.page); groups.set(step.navigation.group, group);
}
const nav = document.createElement('nav');
nav.id = 'appSidebar'; nav.setAttribute('aria-label', 'Fixture navigation');
nav.innerHTML = [...groups].map(([name, links]) => `<section class="shell-nav-group" data-group-label="${name}"><div class="shell-nav-group-items">${[...links].map(([label, page]) => `<a class="shell-link" href="${page}">${label}</a>`).join('')}</div></section>`).join('') + '<div class="shell-account-menu"><a role="menuitem" href="settings.html">Profile &amp; settings</a></div>';
document.body.append(nav);
const clockIn = document.getElementById('mainClockInBtn');
const clockOut = document.getElementById('mainClockOutBtn');
if (clockIn && clockOut) { window.fixtureClock(); window.fixtureSchedule(); }
window.fixtureChat();
// Dynamic row actions are generated by the unmodified production action() function.
const key = document.body.dataset.adminView;
const tbody = document.getElementById('sectionTableBody');
if (tbody) {
  document.getElementById('sectionTitle').textContent = key;
  document.getElementById('sectionTableTitle').textContent = `${key} records`;
  document.getElementById('sectionAction').textContent = 'Page action';
  const records = options.empty ? [] : options.headFirst ? [
    { cells: ['Head administrator', 'head@example.test', 'Admin'], isHeadAdmin: true },
    { cells: ['Employee', 'employee@example.test', 'Employee'] }
  ] : [{ cells: ['Employee', 'employee@example.test', 'Employee'], remarks: [] }];
  tbody.innerHTML = records.length ? records.map((record, i) => `<tr><td>${record.cells[0]}</td><td>${window.fixtureRowAction('Actions', i, key, record)}</td></tr>`).join('') : '<tr><td>No records</td></tr>';
  if (key === 'users') document.querySelector('main').insertAdjacentHTML('afterbegin', '<nav id="adminSectionTabs">Users · Invitations</nav>');
  if (key === 'entries') document.querySelector('main').insertAdjacentHTML('afterbegin', '<section id="activeEntriesPanel">No active entries</section><button id="deletedTimeEntriesButton">Deleted entries</button>');
}
// Static data placeholders keep real empty HTML containers visible, without fabricating tutorial targets.
for (const id of ['timeEntriesList', 'remarksPageList', 'reportsList', 'deletedUsersTable']) {
  const element = document.getElementById(id); if (element && !element.textContent.trim()) element.textContent = 'No records';
}
window.fixtureDocumentId = crypto.randomUUID();
await window.ACETutorial.initialize();
document.documentElement.dataset.fixtureReady = 'true';
